function [usnap] = tstepfemcn0qr(FEM, tlist)
%TSTEPFEMCN0QR Crank – Nicolson time stepper for FEM matrices
% generated by Matlab PDE toolbox
%==========================================================================

dt = tlist(2) - tlist(1);
N = length(tlist) - 1;
M = size(FEM.K, 1); % number of spatial degrees of freedom

usnap = zeros(M, N); % snapshots for all times in tlist except t=0
u0 = zeros(M, 1); % zero initial condition

A    = FEM.M + 0.5*dt*(FEM.K + FEM.Q);
Arhs = FEM.M - 0.5*dt*(FEM.K + FEM.Q);

[QA, RA] = qr(A); % factorize A for multiple linear system solves 

usnap(:, 1) = RA \ (QA' * (Arhs * u0 + dt * FEM.G));

for k = 2:N
    usnap(:, k) = RA \ (QA' * (Arhs * usnap(:, k-1) + dt * FEM.G));
end

end
